version: "3.1"
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081

  practical-work:
      build: ./
      ports:
        - 80:3000
      environment:
        - PORT=3000
        - DB_URL=mongodb://root:example@mongo:27017/
        - DB_NAME=someDB
      depends_on:
        - mongo